name: action_app
description: "Climate Action Platform - Comprehensive climate disaster prediction and monitoring system with business features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.2.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  # Charts for analytics
  syncfusion_flutter_charts: ^30.2.4
  # Basic utilities
  shared_preferences: ^2.2.2
  path: ^1.8.3
  # QR and scanning
  qr_flutter: ^4.1.0
  # Local storage
  path_provider: ^2.1.2
  # Essential humanitarian features
  connectivity_plus: ^5.0.2
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
